app:
  file_link: http://localhost:8080/uploads
server:
  run_mode: debug
  addr: :8080
db:
  driver_name: mysql
  host: 192.168.56.107
  port: 3306
  database: kakaphp
  prefix: kk_
  username: root
  password: admin888
  charset: utf8
redis:
  host: 192.168.56.107
  port: 6379
  password: 
  db: 1
  pool_size: 5
mongo:
  host: 192.168.56.107
  port: 27017
  database: kakaphp
  username: admin
  password: admin888
mail:
  host: smtp.mailgun.org
  port: 587
  username: postmaster@sandbox1be15f57906341ad92f85726a17f63b1.mailgun.org
  password: 55a88ea9fb8efa2976ae0377870ba45d
  encryption: tls
  from_address: postmaster@sandbox1be15f57906341ad92f85726a17f63b1.mailgun.org
  from_name: 平台
telegram_bot:
  token: 5612442673:AAEVZ-dlh8f9YhfWKehw0t_E9b04ZWVYdxc
line_bot:
  token: B31YiKrefxXQxPSstYWyQFSVyImFPzcwAjUCrlti6wX